@startuml
'https://plantuml.com/activity-diagram-beta

start
:nodeCopy = nodeToInsert;
:nodeCopy->key = nodeToInsert->key;

if(list->size <= 0) then (true)
    :appendNode;
    :free nodeCopy;
else (false)
    if(insertBefore) then (true)
        if(previousNode->prev != NULL) then (true)
            :nodeCopy->next = previousNode;
            :nodeCopy->prev = previousNode->prev;
            :previousNode->prev->next = nodeCopy;
            :previousNode->prev = nodeCopy;

        else (false)
            :nodeCopy->next = previousNode;
            :nodeCopy->prev=NULL;
            :previousNode->prev = nodeCopy;
            :list->head = nodeCopy;

        endif
    else (false)
        if(previousNode->next != NULL) then (true)
            :nodeCopy->next = previousNode;
            :nodeCopy->prev = previousNode->next;
            :previousNode->next->prev = nodeCopy;
            :previousNode->next = nodeCopy;

        else (false)
            :appendNode;
            :free(nodeCopy);
        endif

endif
endif

:list->size++;

stop

@enduml
