@startuml
'https://plantuml.com/activity-diagram-beta

start
:nodeCopy = nodeToInsert;
:nodeCopy->key = nodeToInsert->key;

if(list->size <= 0) then (true)
:appendNode;
:free nodeCopy;
else (false)
if(insertBefore) then (true)
if(previousNode->prev != NULL) then (true)
:nodeCopy->next = previousNode;
:nodeCopy->prev = previousNode->prev;
else (false)
if(previousNode->prev == NULL) then (true)
else (false)

endif

endif
else (false)
endif
endif

:list->size++;

stop

@enduml
